// <auto-generated />
using System;
using LivroRazao.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LivroRazao.Infraestrutura.Migracao
{
    [DbContext(typeof(LivroRazaoContexto))]
    [Migration("20260722004436_CriarEstruturaInicial")]
    partial class CriarEstruturaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LivroRazao.Dominio.Caixa.Lancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTimeOffset>("DataLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_LANCAMENTO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("TIPO")
                        .IsFixedLength();

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("TB_LANCAMENTO", (string)null);
                });

            modelBuilder.Entity("LivroRazao.Infraestrutura.Persistencia.Entidades.Outbox.LancamentoOutbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTimeOffset>("DataOcorrencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_OCORRENCIA");

                    b.Property<DateTimeOffset?>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_PUBLICACAO");

                    b.Property<DateTimeOffset?>("DataUltimaTentativa")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ULTIMA_TENTATIVA");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("PAYLOAD");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("TENTATIVAS");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TIPO_EVENTO");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("ULTIMO_ERRO");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("Status", "DataCriacao", "DataUltimaTentativa");

                    b.ToTable("TB_LANCAMENTO_OUTBOX", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
